# entise/methods/heat/districtheatingsim/try_conversion.py

import os
import tempfile
import numpy as np
import pandas as pd


def create_try_file(idx_hour_full: pd.DatetimeIndex, temperature: pd.Series, prefix: str):
    """
    Creates a temporary TRY-format file for DistrictHeatingSim
    using only temperature as meaningful input.

    Returns:
        tmp_dir (str),
        tmp_try_path (str)
    """

    col_widths = [8, 8, 3, 3, 3, 6, 5, 4, 5, 2, 5, 4, 5, 5, 4, 5, 3]
    col_names = [
        "RW", "HW", "MM", "DD", "HH",
        "t", "p", "WR", "WG", "N",
        "x", "RF", "B", "D", "A",
        "E", "IL"
    ]

    n = len(idx_hour_full)

    df_try = pd.DataFrame({name: np.zeros(n, dtype=float) for name in col_names})
    df_try["t"] = temperature.to_numpy(dtype=float)
    df_try["MM"] = idx_hour_full.month.to_numpy()
    df_try["DD"] = idx_hour_full.day.to_numpy()
    df_try["HH"] = (idx_hour_full.hour + 1).to_numpy()  # TRY hour convention 1–24

    tmp_dir = tempfile.mkdtemp(prefix=prefix)
    tmp_try_path = os.path.join(tmp_dir, "TRY_from_weather.dat")

    with open(tmp_try_path, "w", encoding="utf-8") as f:
        for _ in range(34):
            f.write("generated by entise\n")

        for i in range(n):
            vals = []
            for w, col in zip(col_widths, col_names):
                v = df_try.at[i, col]
                if col in ("RW", "HW", "MM", "DD", "HH", "WR", "N", "IL"):
                    s = f"{int(round(v)):d}"
                else:
                    s = f"{float(v):.2f}"
                vals.append(s.rjust(w))
            f.write("".join(vals) + "\n")

    return tmp_dir, tmp_try_path


def cleanup_try_dir(tmp_dir: str):
    """Safely remove temporary TRY directory."""
    try:
        for root, _, files in os.walk(tmp_dir, topdown=False):
            for fn in files:
                os.remove(os.path.join(root, fn))
        os.rmdir(tmp_dir)
    except Exception:
        pass