# Default values for optional keys
DEFAULT_ACTIVE_COOLING: bool = True
DEFAULT_ACTIVE_HEATING: bool = True
DEFAULT_ACTIVE_SOLAR_GAINS: bool = True
DEFAULT_ACTIVE_INTERNAL_GAINS: bool = True
DEFAULT_ACTIVE_VENTILATION: bool = True
DEFAULT_POWER_HEATING: float = float("inf")  # W
DEFAULT_POWER_COOLING: float = float("inf")  # W
DEFAULT_TEMP_INIT: float = 22  # °C
DEFAULT_TEMP_MAX: float = 24  # °C
DEFAULT_TEMP_MIN: float = 20  # °C
DEFAULT_THERMAL_INERTIA: float = 0
DEFAULT_VENTILATION: float = 65  # W/K
DEFAULT_FRAC_CONV_INTERNAL: float = 0.5

# 5R1C-specific defaults
DEFAULT_SIGMA_5R1C: float = 0.0
DEFAULT_FRAC_RAD_SURFACE: float = 0.7
DEFAULT_FRAC_RAD_MASS: float = 0.3
