# Default values for optional keys
DEFAULT_ACTIVE_COOLING = True
DEFAULT_ACTIVE_HEATING = True
DEFAULT_ACTIVE_SOLAR_GAINS = True
DEFAULT_ACTIVE_INTERNAL_GAINS = True
DEFAULT_ACTIVE_VENTILATION = True
DEFAULT_POWER_HEATING = float("inf")  # W
DEFAULT_POWER_COOLING = float("inf")  # W
DEFAULT_TEMP_INIT = 22  # °C
DEFAULT_TEMP_MAX = 24  # °C
DEFAULT_TEMP_MIN = 20  # °C
DEFAULT_THERMAL_INERTIA = 0
DEFAULT_VENTILATION = 65  # W/K (mirrored from auxiliary ventilation due to circular imports)
