class Objects:
    """Keys used for identifying objects and their attributes.
    Sorted alphabetically for easy reference (except for ID).
    """

    ID = "id"  # Unique identifier for an object
    ACTIVE = "active"
    ACTIVE_COOLING = f"{ACTIVE}_cooling"  # Activate cooling?
    ACTIVE_GAINS_INTERNAL = f"{ACTIVE}_gains_internal"  # Activate internal gains?
    ACTIVE_GAINS_SOLAR = f"{ACTIVE}_gains_solar"  # Activate solar gains?
    ACTIVE_HEATING = f"{ACTIVE}_heating"  # Activate heating?
    ACTIVE_VENTILATION = f"{ACTIVE}_ventilation"  # Activate ventilation?
    ALTITUDE = "altitude[m]"  # Altitude (m)
    AREA = "area[m2]"  # Area (m2)
    AREA_M = "area_m[m2]"  # Area of the building mass (m2)
    AREA_TOT = "area_tot[m2]"  # Total area (m2)
    AZIMUTH = "azimuth[degree]"  # Azimuth (degrees; 0/360 = North)
    BASELINE_OFFSET = "baseline_offset"  # Value substracted from moving average, to reduce detection sensitivity
    BUILDING_CLASS = "building_class"
    BUILDING_TYPE = "building_type"
    C_1_AW = "C_1_AW[J K-1]"  # Thermal capacitance of the outer walls (J/K)
    C_1_IW = "C_1_IW[J K-1]"  # Thermal capacitance of the inner walls (J/K)
    C_M = "C_m[J K-1]"  # Thermal capacitance of the building mass (J/K)
    CAPACITANCE = "capacitance[J K-1]"  # Capacitance (J/K)
    CAPACITANCE_AIR = "capacitance_air[J K-1]"  # Air capacitance (J/K)
    COLUMN = "column"
    CORRECTION_FACTOR = "correction_factor"  # Correction factor for calculations
    DATETIMES = "datetimes"
    DEMAND = "demand"
    DEMAND_KWH = "demand[kWh]"
    DETECTION_THRESHOLD = "detection_threshold"  # Minimal value from which occupancy is assigned
    DHW_ACTIVITY = "dhw_activity"  # DHW activity filename
    DHW_DEMAND_PER_SIZE = "dhw_demand_per_size[m2]"  # DHW demand per size, i.e. m2
    DHW_DEMAND_PER_PERSON = "dhw_demand_per_person"  # DHW demand per person
    DWELLING_SIZE = "dwelling_size[m2]"  # Size of dwelling (m2)
    ENERGY_INTENSITY = "energy_intensity"  # Energy intensity mode (string/enum)
    FILE = "filename"  # File
    FRAC_RAD_AW = "fraction_rad_AW"  # Fraction of radiant gains that go to outer walls
    FRAC_CONV_INTERNAL = "fraction_conv_internal"  # Fraction of total gains that is convective to air
    FRAC_RAD_SURFACE = "fraction_rad_surface"  # Fraction of radiant gains that go to surfaces (vs. mass)
    FRAC_RAD_MASS = "fraction_rad_mass"  # Fraction of radiant gains that go to mass
    GAINS_INTERNAL = "gains_internal[W]"  # Internal gains (W)
    GAINS_INTERNAL_COL = f"gains_internal_{COLUMN}"  # column in which the internal gains are (dataframe provided)
    GAINS_INTERNAL_PER_PERSON = f"{GAINS_INTERNAL}_per_person[W]"  # Internal gains per person (W)
    GAINS_SOLAR = "gains_solar[W]"  # Solar gains (W)
    GEN_MAX = "maximum_generation[W]"  # Maximum generation (W)
    GRADIENT_SINK = "gradient_sink"  # Gradient of the sink temperature
    H_TR_EM = "H_tr_em[W K-1]"  # Transmission heat transfer coefficient between thermal mass and exterior (W/K)
    H_TR_IS = "H_tr_is[W K-1]"  # Transmission heat transfer coefficient between indoor air and internal surfaces (W/K)
    H_TR_OP_SKY = "H_tr_op_sky[W K-1]"  # Transmission heat transfer coeff. between outdoor air and sky (W/K)
    H_TR_MS = "H_tr_ms[W K-1]"  # Transmission heat transfer coeff. between thermal mass and internal surfaces (W/K)
    H_TR_W = "H_tr_w[W K-1]"  # Transmission heat transfer coefficient between windows and exterior (W/K)
    H_VE = "H_ve[W K-1]"  # Ventilation heat transfer coefficient between indoor air and exterior (W/K)
    HEIGHT = "height[m]"  # Height (m)
    HOLIDAYS_LOCATION = "holidays_location"  # Location from which to get the holidays from (e.g. BY,DE)
    HOUSEHOLDS = "households"  # Number of households
    HOUSEHOLD_TYPE = "household_type"  # Type of household
    HP_SINK = "hp_sink"  # Heat pump sink type (floor, radiator, water)
    HP_SOURCE = "hp_source"  # Heat pump source type (air, soil, water)
    HP_SYSTEM = "hp_system"  # HP system configuration
    HUB_HEIGHT = "hub_height[m]"  # Hub height (wind)
    INHABITANTS = "inhabitants"  # Number of inhabitants
    LAT = "latitude[degree]"  # Latitude (degree north)
    LOAD = "load"
    LOAD_BASE = f"{LOAD}_base"  # Base load
    LOAD_MAX = f"{LOAD}_max"
    LON = "longitude[degree]"  # Longitude (degree north)
    LAMBDA = "lambda_occ"  # Weighting factor for occupancy, e.g. GeoMA/PHT
    NIGHT_SCHEDULE = "night_schedule"
    NIGHT_SCHEDULE_START = f"{NIGHT_SCHEDULE}_start"  # Start hour for detecting nightly occupancy schedule
    NIGHT_SCHEDULE_END = f"{NIGHT_SCHEDULE}_end"  # End hour for detecting nightly occupancy schedule
    OCCUPANCY = "occupancy"  # Occupancy (for timeseries files)
    OCCUPANCY_AVG = f"average_{OCCUPANCY}"  # Average occupancy over a certain timeseries
    OCCUPANTS = "occupants"  # Number of occupants
    OCCUPANTS_PER_HOUSEHOLD = "occupants_per_household"  # Number of occupants per household
    ORIENTATION = "orientation[degree]"  # Orientation (degrees; 180 = south)
    POWER = "power[W]"  # Power (W)
    POWER_COOLING = "power_cooling[W]"  # Power cooling (W)
    POWER_HEATING = "power_heating[W]"  # Power heating (W)
    PROFILE = "profile"  # Type of profile, e.g. H0 for demandlib electricity
    PV_ARRAYS = "pv_arrays"  # PV array configuration (dict)
    PV_INVERTER = "pv_inverter"  # PV inverter configuration (dict)
    R_1_AW = "R_1_AW[K W-1]"  # Thermal resistance of the outer walls (K/W)
    R_1_IW = "R_1_IW[K W-1]"  # Thermal resistance of the inner walls (K/W)
    R_ALPHA_STAR_AW = "R_alpha_star_AW[K W-1]"  # External surface heat transfer resistance (K/W)
    R_ALPHA_STAR_IL = "R_alpha_star_IL[K W-1]"  # Internal surface heat transfer resistance (K/W)
    R_ALPHA_STAR_IW = "R_alpha_star_IW[K W-1]"  # Internal surface heat transfer resistance (K/W)
    R_REST_AW = "R_rest_AW[K W-1]"  # Thermal resistance of the remaining layers of the outer walls (K/W)
    RESISTANCE = "resistance[K W-1]"  # Resistance (K/W)
    SEASONAL_PEAK_DAY = "seasonal_peak_day"  # Day of year with peak demand
    SEASONAL_VARIATION = "seasonal_variation"  # Seasonal variation factor
    SEED = "seed"  # Seed to ensure reproducibility
    SIGMA = "sigma"  # Standard deviation
    SIGMA_SURFACE = "sigma_surface"  # Sigma for 5R1C radiant internal gains to surfaces
    SIGMA_7R2C_AW = "sigma_7R2C_AW"  # Sigma for 7R2C fraction of radiant internal gains to outer walls
    SIGMA_7R2C_IW = "sigma_7R2C_IW"  # Sigma for 7R2C fraction of radiant internal gains to inner walls
    SOURCE = "source"  # Source of data or method
    T_EQ = "T_eq[C]"  # Equivalent temperature (°C)
    T_EQ_COL = f"{T_EQ}_{COLUMN}"  # Name of column if equivalent temperature is provided in a dataframe
    T_EQ_ALPHA_SW = "T_eq_alpha_SW[1]"  # Shortwave absorptance
    T_EQ_H_O = "T_eq_h_o[W m-2 K-1]"  # Outdoor heat transfer coeff
    TEMP = "temperature[C]"  # Temperature (°C)
    TEMP_WATER = f"water_{TEMP}"  # Water temperature (°C)
    TEMP_WATER_COLD = f"cold_{TEMP_WATER}"  # Cold water temperature (°C)
    TEMP_WATER_HOT = f"hot_{TEMP_WATER}"  # Hot water temperature (°C)
    TEMP_INIT = f"init_{TEMP}"  # Initial temperature (°C)
    TEMP_MAX = f"max_{TEMP}"  # Maximum temperature (°C)
    TEMP_MIN = f"min_{TEMP}"  # Minimum temperature (°C)
    TEMP_SET = f"set_{TEMP}"  # Set temperature (°C)
    TEMP_SINK = f"sink_{TEMP}"  # Heat pump sink temperature setting (°C)
    TEMP_SUPPLY = f"supply_{TEMP}"  # Supply temperature (°C)
    THERMAL_INERTIA = "thermal_inertia"  # Thermal inertia [0, 1]
    TILT = "tilt[degree]"  # Tilt (degrees; 0 = horizontal)
    TRANSMITTANCE = "transmittance[W m-2 K-1]"  # Transmittance (W/m2/K)
    TURBINE_TYPE = "turbine_type"  # Turbine type (wind)
    VENTILATION = "ventilation[W K-1]"  # Ventilation losses (W/K)
    VENTILATION_COL = f"ventilation_{COLUMN}"
    VENTILATION_FACTOR = "ventilation_factor[h-1]"  # 1/h
    VENTILATION_SPLIT = "ventilation_split"  # Ventilation split factor
    VERBOSE = "verbose"  # Verbose
    WEATHER = "weather"  # Weather
    WIND_CLASS = "wind_class"
    WIND_MODEL = "wind_model"  # Model chain (wind)
    WINDOWS = "windows"  # Windows
    YEARLY_DHW_DEMAND = "yearly_dhw_demand[m3 m-2 a-1]"  # Yearly DHW demand in m³ per m²
